extends:
  - google
  - plugin:node/recommended
plugins:
  - markdown
  - node
rules:
  # Javascript feature preference
  no-var: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-template: error
